spring.application.name=praksa

spring.config.import=optional:env.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/praksaDb
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName = org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.ai.vectorstore.pgvector.initialize-schema=true
app.vector-store.reload=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.default_schema = public

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536

spring.data.neo4j.database=neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${NEO4j_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.chat.enabled=false

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-6

spring.jpa.open-in-view=true


